# Generated by Django 5.2.13 on 2026-07-28 11:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymize_ip', models.BooleanField(default=True, help_text='Hash IP addresses with SHA256 before storing')),
                ('ignored_prefixes', models.TextField(default='/admin/\n/static/\n/media/', help_text='One path prefix per line. Requests starting with these will not be logged.')),
                ('ignored_extensions', models.TextField(default='.css\n.js\n.png\n.jpg\n.svg\n.ico\n.woff2', help_text='One extension per line. Requests to these file types will not be logged.')),
                ('realtime_refresh_seconds', models.PositiveIntegerField(default=30, help_text='How often (in seconds) the real‑time dashboard refreshes')),
                ('tracked_paths', models.TextField(blank=True, help_text='One path prefix per line. If non‑empty, ONLY these paths will be logged (ignored_paths still apply).')),
                ('bot_paths', models.TextField(blank=True, help_text='One path prefix per line. Requests to these paths are counted as bot traffic (shown separately).')),
            ],
            options={
                'verbose_name': 'Analytics Settings',
                'verbose_name_plural': 'Analytics Settings',
            },
        ),
        migrations.CreateModel(
            name='BackupArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Name of the backup file (e.g., backup_20250320_123456.tar.gz)', max_length=255)),
                ('size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('storage_path', models.CharField(help_text='Absolute path to the backup file on disk', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Backup Archive',
                'verbose_name_plural': 'Backup Archives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_paths', models.TextField(blank=True, help_text='One path per line (absolute or relative to the project root). Directories and files to include.')),
                ('storage_path', models.CharField(blank=True, help_text='Absolute path where backup archives will be stored. Must be writable by the web server.', max_length=500)),
                ('enabled', models.BooleanField(default=False, help_text='Enable automatic backups (scheduled via cron).')),
                ('schedule', models.CharField(choices=[('manual', 'Manual only'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='manual', help_text='How often to create backups (requires cron to run the management command).', max_length=20)),
                ('retention_count', models.PositiveIntegerField(default=5, help_text='Number of most recent backups to keep. Older backups are automatically deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Configuration',
                'verbose_name_plural': 'Backup Configurations',
            },
        ),
        migrations.CreateModel(
            name='DailySiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_ips', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('api_calls', models.PositiveIntegerField(default=0)),
                ('top_pages', models.JSONField(blank=True, default=dict)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('bounces', models.PositiveIntegerField(default=0)),
                ('bot_views', models.PositiveIntegerField(default=0, help_text='Requests to paths marked as bot/scanner traffic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Site Stats',
                'verbose_name_plural': 'Daily Site Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('total_size', models.BigIntegerField(help_text='Expected total size in bytes, sent by client at init')),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('chunk_size', models.IntegerField(help_text='Size of each chunk in bytes, as used by the client')),
                ('total_chunks', models.IntegerField()),
                ('chunks_received', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('storage_path', models.CharField(help_text='Absolute path to the file on disk once completed', max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Upload',
                'verbose_name_plural': 'File Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2048)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('is_bot', models.BooleanField(default=False, help_text='True if the request path matches a bot path.')),
                ('method', models.CharField(default='GET', max_length=10)),
                ('status_code', models.PositiveIntegerField(default=200)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=2048)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-created_at'],
            },
        ),
    ]
