# Generated by Django 5.2.13 on 2026-05-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymize_ip', models.BooleanField(default=True, help_text='Hash IP addresses with SHA256 before storing')),
                ('ignored_prefixes', models.TextField(default='/admin/\n/static/\n/media/', help_text='One path prefix per line. Requests starting with these will not be logged.')),
                ('ignored_extensions', models.TextField(default='.css\n.js\n.png\n.jpg\n.svg\n.ico\n.woff2', help_text='One extension per line. Requests to these file types will not be logged.')),
                ('realtime_refresh_seconds', models.PositiveIntegerField(default=30, help_text='How often (in seconds) the real‑time dashboard refreshes')),
            ],
            options={
                'verbose_name': 'Analytics Settings',
                'verbose_name_plural': 'Analytics Settings',
            },
        ),
    ]
