# Generated by Django 5.2.13 on 2026-05-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analyticssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysitestats',
            name='bounces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysitestats',
            name='total_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pageview',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
