# Generated by Django 5.2.13 on 2026-05-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_dailysitestats_bounces_dailysitestats_total_sessions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
