# Generated by Django 5.2.13 on 2026-06-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssettings',
            name='bot_paths',
            field=models.TextField(blank=True, help_text='One path prefix per line. Requests to these paths are counted as bot traffic (shown separately).'),
        ),
        migrations.AddField(
            model_name='analyticssettings',
            name='tracked_paths',
            field=models.TextField(blank=True, help_text='One path prefix per line. If non‑empty, ONLY these paths will be logged (ignored_paths still apply).'),
        ),
        migrations.AddField(
            model_name='dailysitestats',
            name='bot_views',
            field=models.PositiveIntegerField(default=0, help_text='Requests to paths marked as bot/scanner traffic'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='is_bot',
            field=models.BooleanField(default=False, help_text='True if the request path matches a bot path.'),
        ),
    ]
