# Generated by Django 5.2.13 on 2026-06-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_analyticssettings_bot_paths_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Name of the backup file (e.g., backup_20250320_123456.tar.gz)', max_length=255)),
                ('size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('storage_path', models.CharField(help_text='Absolute path to the backup file on disk', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Backup Archive',
                'verbose_name_plural': 'Backup Archives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_paths', models.TextField(blank=True, help_text='One path per line (absolute or relative to the project root). Directories and files to include.')),
                ('storage_path', models.CharField(blank=True, help_text='Absolute path where backup archives will be stored. Must be writable by the web server.', max_length=500)),
                ('enabled', models.BooleanField(default=False, help_text='Enable automatic backups (scheduled via cron).')),
                ('schedule', models.CharField(choices=[('manual', 'Manual only'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='manual', help_text='How often to create backups (requires cron to run the management command).', max_length=20)),
                ('retention_count', models.PositiveIntegerField(default=5, help_text='Number of most recent backups to keep. Older backups are automatically deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Configuration',
                'verbose_name_plural': 'Backup Configurations',
            },
        ),
    ]
