# Generated by Django 5.2.13 on 2026-06-25 10:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_backuparchive_backupconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuparchive',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
